version: '3'
services:

  db:
    restart: always
    image: postgres:9.6-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - ./postgres:/var/lib/postgresql/data
    logging:
      driver: "syslog"
      options:
        tag: "bananadog_db"

  redis:
    restart: always
    image: redis:4.0-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data
    logging:
      driver: "syslog"
      options:
        tag: "bananadog_redis"
#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    networks:
#      - external_network
#      - internal_network
#    healthcheck:
#      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
#    volumes:
#      - ./elasticsearch:/usr/share/elasticsearch/data

  web:
    build: .
    image: usbsnowcrash/mastodon
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --header 'x-forwarded-proto: https' --proxy off localhost:3000/api/v1/instance || exit 1"]
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
      - redis
      - tor
      - privoxy
    volumes:
      - ./public/system:/mastodon/public/system
    logging:
      driver: "syslog"
      options:
        tag: "bananadog_web"

  streaming:
    build: .
    image: usbsnowcrash/mastodon
    restart: always
    env_file: .env.production
    command: yarn start
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --header 'x-forwarded-proto: https' --proxy off localhost:4000/api/v1/streaming/health || exit 1"]
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis
      - tor
      - privoxy
    logging:
      driver: "syslog"
      options:
        tag: "bananadog_streaming"

  sidekiq:
    build: .
    image: usbsnowcrash/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
      - tor
      - privoxy
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
    logging:
      driver: "syslog"
      options:
        tag: "bananadog_sidekiq"

  tor:
    build: https://github.com/usbsnowcrash/docker-tor.git
    networks:
      - external_network
      - internal_network
    logging:
      driver: "syslog"
      options:
        tag: "bananadog_tor"

  privoxy:
    build: https://github.com/usbsnowcrash/docker-privoxy.git
    command: /opt/sbin/privoxy --no-daemon --user privoxy.privoxy /opt/config
    volumes:
      - ./priv-config:/opt/config
    networks:
      - external_network
      - internal_network
    logging:
      driver: "syslog"
      options:
        tag: "bananadog_privoxy"

networks:
  external_network:
  internal_network:
    internal: true
